% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Actividad 3},
  pdfauthor={Stefania Astudillo Bello},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Actividad 3}
\author{Stefania Astudillo Bello}
\date{}

\begin{document}
\maketitle

\hypertarget{problema}{%
\subsection{Problema}\label{problema}}

Con base en los datos de ofertas de vivienda descargadas del portal
Fincaraiz para apartamento de estrato 4 con área construida menor a 200
\(m^2\) (vivienda4.RDS) la inmobiliaria A\&C requiere el apoyo en la
construcción de un modelo que lo oriente sobre los precios de inmuebles.

Con este propósito el equipo de asesores a diseñado los siguientes pasos
para obtener un modelo y así poder a futuro determinar los precios de
los inmuebles a negociar

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{viviendas }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\AttributeTok{file =} \StringTok{"vivienda4.RDS"}\NormalTok{)}
\FunctionTok{head}\NormalTok{(viviendas)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 5
##   zona       estrato preciom areaconst tipo       
##   <fct>      <fct>     <dbl>     <dbl> <fct>      
## 1 Zona Norte 4           220        52 Apartamento
## 2 Zona Norte 4           600       160 Casa       
## 3 Zona Norte 4           320       108 Apartamento
## 4 Zona Sur   4           290        96 Apartamento
## 5 Zona Norte 4           220        82 Apartamento
## 6 Zona Norte 4           305       117 Casa
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Realice un análisis exploratorio de las variables precio de vivienda
  (millones de pesos COP) y área de la vivienda (metros cuadrados) -
  incluir gráficos e indicadores apropiados interpretados.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{hist}\NormalTok{(viviendas}\SpecialCharTok{$}\NormalTok{areaconst, }\AttributeTok{xlab =} \StringTok{"Area"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Cantidad"}\NormalTok{, }\AttributeTok{col=}\StringTok{"pink"}\NormalTok{,}
     \AttributeTok{main=}\StringTok{"Histograma de la variable areaconst"}\NormalTok{)}

\FunctionTok{boxplot}\NormalTok{(viviendas}\SpecialCharTok{$}\NormalTok{areaconst, }\AttributeTok{col=}\StringTok{"pink"}\NormalTok{,}
        \AttributeTok{main=}\StringTok{"Caja de la variable areaconst"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Activity3_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datosArea }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(viviendas}\SpecialCharTok{$}\NormalTok{areaconst)}
\NormalTok{datosArea}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   40.00   60.00   75.00   87.63   98.00  200.00
\end{verbatim}

el promedio del área construida de la oferta de viviendas es de 87.63
\(m^2\) para áreas que oscilan entre los 40 \(m^2\) (mínimo) y los 200
\(m^2\) (máximo). La distribución del área de las viviendas si muestra
un sesgo bastante pronunciado a la derecha; podemos observar que el 50\%
de las viviendas tienen entre 40 \(m^2\) y 75 \(m^2\) mientras que el
otro 50\% tiene entre 75 \(m^2\) y 200 \(m^2\).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\FunctionTok{hist}\NormalTok{(viviendas}\SpecialCharTok{$}\NormalTok{preciom, }\AttributeTok{xlab =} \StringTok{"precio"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Cantidad"}\NormalTok{, }\AttributeTok{col=}\StringTok{"pink"}\NormalTok{,}
     \AttributeTok{main=}\StringTok{"Histograma de la variable preciom"}\NormalTok{)}

\FunctionTok{boxplot}\NormalTok{(viviendas}\SpecialCharTok{$}\NormalTok{preciom, }\AttributeTok{col=}\StringTok{"pink"}\NormalTok{,}
        \AttributeTok{main=}\StringTok{"Caja de la variable preciom"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Activity3_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datosPrecio }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(viviendas}\SpecialCharTok{$}\NormalTok{preciom)}
\NormalTok{datosPrecio}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    78.0   160.0   210.0   225.4   265.0   760.0
\end{verbatim}

Los datos nos revelan que el promedio del precio de la oferta de
viviendas es de 225.4 millones, para valores que oscilan entre los 78
millones (mínimo) y los 760 millones (máximo). podemos precisar que la
mitad de las viviendas se oferta a un precio menor o igual a los 210
millones y sólo un 25\% están en un rango de costosas superando los 265
millones de pesos colombianos.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Realice un análisis exploratorio bivariado de datos enfocado en la
  relación entre la variable respuesta (precio) en función de la
  variable predictora (área construida) - incluir gráficos e indicadores
  apropiados interpretados.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(viviendas}\SpecialCharTok{$}\NormalTok{areaconst, viviendas}\SpecialCharTok{$}\NormalTok{preciom, }
     \AttributeTok{xlab =} \StringTok{"Area construida"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"Precio millones"}\NormalTok{, }
     \AttributeTok{main=}\StringTok{"Analisis Exploratorio bivariado Area/Precio"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Activity3_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(viviendas}\SpecialCharTok{$}\NormalTok{areaconst,viviendas}\SpecialCharTok{$}\NormalTok{preciom)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7630166
\end{verbatim}

Observando la gráfica de dispersión podemos destacar una tendencia
directa o creciente en la relación del área construida con el precio de
la vivienda, sin embargo, el comportamiento del precio es más disperso
para áreas mayores a 100 \(m^2\), lo que puede dificultar la
representatividad de un modelo de regresión lineal. Observando el
Coeficiente de Correlación de Pearson (0.76) podemos determinar que la
asociación que mide la relación lineal entre el precio y el área
construida es una relación lineal positiva débil.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Estime el modelo de regresión lineal simple entre
  \(precio=f(area)+\epsilon\). Interprete los coeficientes del modelo
  \(\beta0, \beta1\) en caso de ser correcto.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(viviendas}\SpecialCharTok{$}\NormalTok{preciom}\SpecialCharTok{\textasciitilde{}}\NormalTok{viviendas}\SpecialCharTok{$}\NormalTok{areaconst)}
\FunctionTok{summary}\NormalTok{(mod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = viviendas$preciom ~ viviendas$areaconst)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -195.86  -31.95   -8.95   27.87  431.17 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(>|t|)    
## (Intercept)           67.381      3.510   19.20   <2e-16 ***
## viviendas$areaconst    1.803      0.037   48.73   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 55.53 on 1704 degrees of freedom
## Multiple R-squared:  0.5822, Adjusted R-squared:  0.5819 
## F-statistic:  2374 on 1 and 1704 DF,  p-value: < 2.2e-16
\end{verbatim}

El modelo de regresión lineal se estima en:
\(Precio = 67.381 + 1.803 * Area_Contruida\)

\(\beta0\) = 67.381, este coeficiente nos indica el valor de la variable
precio cuando no se tiene una vivienda construida, se podría pensar que
es el valor base del terreno.

\(\beta1\) = 1.803, indica que por cada metro cuadrado construido el
valor de la vivienda incrementara 1.803 millones aproximadamente.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Construir un intervalo de confianza (95\%) para el coeficiente
  \(\beta1\), interpretar y concluir si el coeficiente es igual a cero o
  no. Compare este resultado con una prueba de hipótesis t.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{confint}\NormalTok{(mod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                         2.5 %    97.5 %
## (Intercept)         60.496208 74.265055
## viviendas$areaconst  1.730404  1.875547
\end{verbatim}

Con un nivel de confianza del 95\% y un 5\% de error \(\alpha\), podemos
determinar que el coeficiente \(\beta1\) para el caso del área
construida podría tomar un valor entre los 1,73 y los 1,87 millones por
cada metro cuadrado construido. dado que el 0 no esta incluido en el
intervalo de confianza, podemos concluir que se rechaza la hipótesis
nula y se concluye que hay suficiente evidencia para no aceptar la
nulidad de este coeficiente. Si comparamos este resultado con la prueba
t que nos da el output del punto anterior, el p-value para el
coeficiente \(\beta1\) fue \(2.2e-16\), esto apoya el rechazo de la
hipótesis de nulidad y apoya la conclusión obtenida con el intervalo de
confianza.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Calcule e interprete el indicador de bondad y ajuste \(R^2\).
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{r2 }\OtherTok{=} \FunctionTok{summary}\NormalTok{(mod)}\SpecialCharTok{$}\NormalTok{r.squared}
\FunctionTok{print}\NormalTok{( }\FunctionTok{paste}\NormalTok{(}\StringTok{"Coeficiente de determinación (R2): "}\NormalTok{, r2) )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Coeficiente de determinación (R2):  0.582194373334701"
\end{verbatim}

El indicador de bondad y ajuste para esta relación es de 0.58, esto
quiere decir que el modelo explica un 58\% de la variación del precio de
la vivienda. De forma general podemos decir que el modelo tiene poca
fuerza para predecir a la variable dependiente.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  ¿Cuál sería el precio promedio estimado para un apartamento de 110
  metros cuadrados? Considera entonces con este resultado que un
  apartamento en la misma zona con 110 metros cuadrados en un precio de
  200 millones sería una atractiva esta oferta? ¿Qué consideraciones
  adicionales se deben tener?.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(mod, }\AttributeTok{newdata =} \FunctionTok{list}\NormalTok{(}\AttributeTok{Area\_contruida=}\DecValTok{110}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        1        2        3        4        5        6        7        8 
## 161.1354 355.8567 262.1020 240.4663 215.2246 278.3288 202.6038 175.5592 
##        9       10       11       12       13       14       15       16 
## 218.8306 278.3288 280.1318 175.5592 202.6038 204.4068 166.5443 179.1651 
##       17       18       19       20       21       22       23       24 
## 175.5592 274.7228 175.5592 180.9681 200.8008 171.9532 184.5740 184.5740 
##       25       26       27       28       29       30       31       32 
## 180.9681 173.7562 171.9532 409.9460 424.3698 391.9162 296.3585 314.3883 
##       33       34       35       36       37       38       39       40 
## 211.6187 208.0127 217.0276 157.5294 177.3621 177.3621 166.5443 182.7711 
##       41       42       43       44       45       46       47       48 
## 159.3324 175.5592 191.7859 177.3621 177.3621 179.1651 168.3473 157.5294 
##       49       50       51       52       53       54       55       56 
## 177.3621 162.9383 157.5294 157.5294 168.3473 180.9681 180.9681 162.9383 
##       57       58       59       60       61       62       63       64 
## 175.5592 283.7377 175.5592 179.1651 166.5443 175.5592 208.0127 175.5592 
##       65       66       67       68       69       70       71       72 
## 238.6633 202.6038 218.8306 294.5556 283.7377 274.7228 226.0425 179.1651 
##       73       74       75       76       77       78       79       80 
## 191.7859 173.7562 179.1651 152.1205 175.5592 222.4365 182.7711 175.5592 
##       81       82       83       84       85       86       87       88 
## 218.8306 197.1949 175.5592 191.7859 175.5592 170.1502 184.5740 193.5889 
##       89       90       91       92       93       94       95       96 
## 222.4365 197.1949 186.3770 175.5592 197.1949 175.5592 175.5592 171.9532 
##       97       98       99      100      101      102      103      104 
## 175.5592 180.9681 197.1949 184.5740 227.8455 260.2990 197.1949 211.6187 
##      105      106      107      108      109      110      111      112 
## 177.3621 262.1020 262.1020 262.1020 197.1949 262.1020 229.6484 240.4663 
##      113      114      115      116      117      118      119      120 
## 426.1728 166.5443 175.5592 184.5740 189.9830 193.5889 195.3919 195.3919 
##      121      122      123      124      125      126      127      128 
## 171.9532 180.9681 175.5592 202.6038 229.6484 251.2841 159.3324 189.9830 
##      129      130      131      132      133      134      135      136 
## 258.4960 220.6336 198.9979 222.4365 229.6484 355.8567 427.9758 283.7377 
##      137      138      139      140      141      142      143      144 
## 164.7413 157.5294 229.6484 301.7675 283.7377 200.8008 283.7377 314.3883 
##      145      146      147      148      149      150      151      152 
## 301.7675 227.8455 182.7711 265.7079 204.4068 294.5556 262.1020 290.9496 
##      153      154      155      156      157      158      159      160 
## 427.9758 193.5889 211.6187 157.5294 168.3473 166.5443 202.6038 161.1354 
##      161      162      163      164      165      166      167      168 
## 391.9162 366.6746 189.9830 308.9794 247.6782 179.1651 323.4032 175.5592 
##      169      170      171      172      173      174      175      176 
## 186.3770 373.8865 319.7972 373.8865 175.5592 206.2098 290.9496 244.0722 
##      177      178      179      180      181      182      183      184 
## 307.1764 180.9681 168.3473 220.6336 173.7562 155.7264 162.9383 208.0127 
##      185      186      187      188      189      190      191      192 
## 240.4663 175.5592 175.5592 184.5740 171.9532 159.3324 170.1502 184.5740 
##      193      194      195      196      197      198      199      200 
## 175.5592 175.5592 166.5443 227.8455 164.7413 211.6187 171.9532 220.6336 
##      201      202      203      204      205      206      207      208 
## 220.6336 274.7228 220.6336 393.7192 215.2246 238.6633 159.3324 159.3324 
##      209      210      211      212      213      214      215      216 
## 162.9383 222.4365 409.9460 258.4960 328.8121 217.0276 391.9162 254.8901 
##      217      218      219      220      221      222      223      224 
## 427.9758 280.1318 229.6484 211.6187 238.6633 242.2693 229.6484 240.4663 
##      225      226      227      228      229      230      231      232 
## 202.6038 292.7526 328.8121 202.6038 323.4032 413.5520 382.9014 391.9162 
##      233      234      235      236      237      238      239      240 
## 350.4478 294.5556 427.9758 382.9014 244.0722 236.8603 283.7377 229.6484 
##      241      242      243      244      245      246      247      248 
## 179.1651 355.8567 391.9162 283.7377 229.6484 238.6633 337.8270 409.9460 
##      249      250      251      252      253      254      255      256 
## 409.9460 427.9758 352.2508 361.2657 373.8865 359.4627 391.9162 400.9311 
##      257      258      259      260      261      262      263      264 
## 391.9162 427.9758 391.9162 229.6484 229.6484 184.5740 409.9460 193.5889 
##      265      266      267      268      269      270      271      272 
## 182.7711 193.5889 328.8121 427.9758 391.9162 391.9162 345.0389 191.7859 
##      273      274      275      276      277      278      279      280 
## 184.5740 184.5740 253.0871 229.6484 319.7972 427.9758 391.9162 400.9311 
##      281      282      283      284      285      286      287      288 
## 175.5592 337.8270 229.6484 359.4627 319.7972 301.7675 283.7377 184.5740 
##      289      290      291      292      293      294      295      296 
## 168.3473 370.2805 337.8270 391.9162 413.5520 245.8752 244.0722 197.1949 
##      297      298      299      300      301      302      303      304 
## 164.7413 197.1949 177.3621 175.5592 180.9681 179.1651 180.9681 184.5740 
##      305      306      307      308      309      310      311      312 
## 197.1949 175.5592 180.9681 180.9681 186.3770 173.7562 179.1651 171.9532 
##      313      314      315      316      317      318      319      320 
## 206.2098 211.6187 202.6038 198.9979 206.2098 206.2098 180.9681 175.5592 
##      321      322      323      324      325      326      327      328 
## 188.1800 191.7859 175.5592 222.4365 195.3919 202.6038 272.9199 240.4663 
##      329      330      331      332      333      334      335      336 
## 202.6038 218.8306 244.0722 206.2098 179.1651 202.6038 168.3473 177.3621 
##      337      338      339      340      341      342      343      344 
## 175.5592 337.8270 173.7562 202.6038 208.0127 152.1205 152.1205 427.9758 
##      345      346      347      348      349      350      351      352 
## 391.9162 195.3919 391.9162 175.5592 175.5592 175.5592 175.5592 211.6187 
##      353      354      355      356      357      358      359      360 
## 175.5592 301.7675 427.9758 182.7711 391.9162 285.5407 168.3473 325.2061 
##      361      362      363      364      365      366      367      368 
## 175.5592 166.5443 200.8008 175.5592 193.5889 186.3770 208.0127 198.9979 
##      369      370      371      372      373      374      375      376 
## 427.9758 168.3473 368.4776 206.2098 427.9758 215.2246 316.1913 197.1949 
##      377      378      379      380      381      382      383      384 
## 427.9758 290.9496 184.5740 208.0127 289.1466 292.7526 193.5889 198.9979 
##      385      386      387      388      389      390      391      392 
## 175.5592 283.7377 238.6633 229.6484 287.3437 197.1949 197.1949 211.6187 
##      393      394      395      396      397      398      399      400 
## 299.9645 229.6484 240.4663 364.8716 312.5853 312.5853 359.4627 173.7562 
##      401      402      403      404      405      406      407      408 
## 197.1949 175.5592 184.5740 274.7228 211.6187 189.9830 175.5592 184.5740 
##      409      410      411      412      413      414      415      416 
## 184.5740 162.9383 211.6187 355.8567 363.0686 175.5592 211.6187 170.1502 
##      417      418      419      420      421      422      423      424 
## 166.5443 170.1502 166.5443 171.9532 170.1502 175.5592 236.8603 395.5222 
##      425      426      427      428      429      430      431      432 
## 316.1913 161.1354 175.5592 170.1502 377.4924 373.8865 427.9758 406.3400 
##      433      434      435      436      437      438      439      440 
## 193.5889 217.0276 164.7413 391.9162 229.6484 247.6782 164.7413 164.7413 
##      441      442      443      444      445      446      447      448 
## 355.8567 162.9383 184.5740 373.8865 247.6782 382.9014 337.8270 292.7526 
##      449      450      451      452      453      454      455      456 
## 373.8865 222.4365 427.9758 327.0091 197.1949 175.5592 171.9532 175.5592 
##      457      458      459      460      461      462      463      464 
## 166.5443 166.5443 168.3473 175.5592 283.7377 168.3473 211.6187 168.3473 
##      465      466      467      468      469      470      471      472 
## 168.3473 229.6484 413.5520 229.6484 208.0127 215.2246 337.8270 177.3621 
##      473      474      475      476      477      478      479      480 
## 233.2544 175.5592 164.7413 171.9532 171.9532 424.3698 171.9532 233.2544 
##      481      482      483      484      485      486      487      488 
## 166.5443 164.7413 164.7413 215.2246 215.2246 168.3473 153.9235 157.5294 
##      489      490      491      492      493      494      495      496 
## 162.9383 175.5592 171.9532 209.8157 157.5294 164.7413 240.4663 240.4663 
##      497      498      499      500      501      502      503      504 
## 202.6038 175.5592 233.2544 233.2544 175.5592 148.5145 175.5592 175.5592 
##      505      506      507      508      509      510      511      512 
## 170.1502 175.5592 175.5592 171.9532 173.7562 180.9681 180.9681 171.9532 
##      513      514      515      516      517      518      519      520 
## 220.6336 229.6484 218.8306 337.8270 373.8865 175.5592 184.5740 337.8270 
##      521      522      523      524      525      526      527      528 
## 170.1502 175.5592 182.7711 166.5443 161.1354 173.7562 267.5109 348.6448 
##      529      530      531      532      533      534      535      536 
## 393.7192 175.5592 355.8567 229.6484 175.5592 229.6484 283.7377 229.6484 
##      537      538      539      540      541      542      543      544 
## 204.4068 233.2544 305.3734 373.8865 184.5740 155.7264 179.1651 294.5556 
##      545      546      547      548      549      550      551      552 
## 229.6484 328.8121 424.3698 415.3549 220.6336 422.5668 384.7043 339.6299 
##      553      554      555      556      557      558      559      560 
## 292.7526 285.5407 316.1913 249.4812 418.9609 231.4514 265.7079 355.8567 
##      561      562      563      564      565      566      567      568 
## 191.7859 226.0425 247.6782 265.7079 191.7859 235.0574 197.1949 179.1651 
##      569      570      571      572      573      574      575      576 
## 161.1354 180.9681 184.5740 236.8603 161.1354 180.9681 222.4365 175.5592 
##      577      578      579      580      581      582      583      584 
## 202.6038 229.6484 229.6484 202.6038 182.7711 191.7859 209.8157 166.5443 
##      585      586      587      588      589      590      591      592 
## 229.6484 238.6633 217.0276 256.6931 220.6336 238.6633 233.2544 229.6484 
##      593      594      595      596      597      598      599      600 
## 256.6931 242.2693 202.6038 193.5889 262.1020 202.6038 180.9681 189.9830 
##      601      602      603      604      605      606      607      608 
## 202.6038 220.6336 202.6038 265.7079 327.0091 179.1651 175.5592 220.6336 
##      609      610      611      612      613      614      615      616 
## 220.6336 215.2246 265.7079 247.6782 312.5853 283.7377 198.9979 202.6038 
##      617      618      619      620      621      622      623      624 
## 301.7675 202.6038 233.2544 346.8419 328.8121 208.0127 319.7972 247.6782 
##      625      626      627      628      629      630      631      632 
## 208.0127 427.9758 208.0127 197.1949 211.6187 301.7675 202.6038 202.6038 
##      633      634      635      636      637      638      639      640 
## 189.9830 301.7675 337.8270 271.1169 271.1169 271.1169 301.7675 166.5443 
##      641      642      643      644      645      646      647      648 
## 202.6038 265.7079 229.6484 236.8603 229.6484 191.7859 166.5443 287.3437 
##      649      650      651      652      653      654      655      656 
## 236.8603 236.8603 236.8603 193.5889 254.8901 200.8008 168.3473 202.6038 
##      657      658      659      660      661      662      663      664 
## 200.8008 247.6782 200.8008 222.4365 222.4365 189.9830 206.2098 206.2098 
##      665      666      667      668      669      670      671      672 
## 206.2098 189.9830 265.7079 206.2098 204.4068 211.6187 157.5294 208.0127 
##      673      674      675      676      677      678      679      680 
## 224.2395 341.4329 233.2544 292.7526 283.7377 319.7972 180.9681 208.0127 
##      681      682      683      684      685      686      687      688 
## 242.2693 197.1949 198.9979 240.4663 184.5740 220.6336 175.5592 170.1502 
##      689      690      691      692      693      694      695      696 
## 168.3473 373.8865 193.5889 229.6484 265.7079 184.5740 197.1949 420.7639 
##      697      698      699      700      701      702      703      704 
## 218.8306 222.4365 233.2544 220.6336 206.2098 238.6633 244.0722 220.6336 
##      705      706      707      708      709      710      711      712 
## 262.1020 244.0722 198.9979 294.5556 202.6038 211.6187 204.4068 289.1466 
##      713      714      715      716      717      718      719      720 
## 238.6633 164.7413 175.5592 204.4068 229.6484 247.6782 229.6484 217.0276 
##      721      722      723      724      725      726      727      728 
## 198.9979 184.5740 301.7675 292.7526 409.9460 211.6187 283.7377 175.5592 
##      729      730      731      732      733      734      735      736 
## 175.5592 220.6336 391.9162 175.5592 184.5740 175.5592 220.6336 265.7079 
##      737      738      739      740      741      742      743      744 
## 184.5740 184.5740 184.5740 247.6782 208.0127 247.6782 245.8752 184.5740 
##      745      746      747      748      749      750      751      752 
## 249.4812 166.5443 193.5889 260.2990 175.5592 265.7079 220.6336 197.1949 
##      753      754      755      756      757      758      759      760 
## 424.3698 319.7972 298.1615 247.6782 332.4180 319.7972 427.9758 319.7972 
##      761      762      763      764      765      766      767      768 
## 413.5520 283.7377 346.8419 189.9830 193.5889 247.6782 218.8306 182.7711 
##      769      770      771      772      773      774      775      776 
## 171.9532 391.9162 310.7823 168.3473 265.7079 209.8157 229.6484 265.7079 
##      777      778      779      780      781      782      783      784 
## 220.6336 307.1764 265.7079 427.9758 226.0425 229.6484 209.8157 258.4960 
##      785      786      787      788      789      790      791      792 
## 218.8306 274.7228 427.9758 327.0091 319.7972 200.8008 269.3139 166.5443 
##      793      794      795      796      797      798      799      800 
## 197.1949 184.5740 197.1949 215.2246 283.7377 229.6484 217.0276 283.7377 
##      801      802      803      804      805      806      807      808 
## 162.9383 150.3175 220.6336 202.6038 220.6336 171.9532 171.9532 171.9532 
##      809      810      811      812      813      814      815      816 
## 218.8306 171.9532 182.7711 175.5592 175.5592 175.5592 171.9532 171.9532 
##      817      818      819      820      821      822      823      824 
## 171.9532 285.5407 175.5592 184.5740 198.9979 180.9681 162.9383 236.8603 
##      825      826      827      828      829      830      831      832 
## 166.5443 175.5592 153.9235 372.0835 310.7823 325.2061 218.8306 195.3919 
##      833      834      835      836      837      838      839      840 
## 427.9758 427.9758 236.8603 236.8603 424.3698 391.9162 244.0722 247.6782 
##      841      842      843      844      845      846      847      848 
## 253.0871 186.3770 247.6782 244.0722 256.6931 157.5294 355.8567 328.8121 
##      849      850      851      852      853      854      855      856 
## 283.7377 175.5592 186.3770 206.2098 215.2246 211.6187 301.7675 209.8157 
##      857      858      859      860      861      862      863      864 
## 208.0127 200.8008 208.0127 211.6187 206.2098 204.4068 206.2098 215.2246 
##      865      866      867      868      869      870      871      872 
## 211.6187 211.6187 200.8008 208.0127 283.7377 208.0127 206.2098 211.6187 
##      873      874      875      876      877      878      879      880 
## 245.8752 197.1949 206.2098 258.4960 247.6782 265.7079 245.8752 247.6782 
##      881      882      883      884      885      886      887      888 
## 220.6336 193.5889 197.1949 399.1281 427.9758 233.2544 218.8306 397.3252 
##      889      890      891      892      893      894      895      896 
## 182.7711 355.8567 218.8306 198.9979 197.1949 217.0276 197.1949 202.6038 
##      897      898      899      900      901      902      903      904 
## 245.8752 200.8008 197.1949 195.3919 206.2098 202.6038 229.6484 206.2098 
##      905      906      907      908      909      910      911      912 
## 206.2098 177.3621 200.8008 206.2098 206.2098 175.5592 180.9681 177.3621 
##      913      914      915      916      917      918      919      920 
## 166.5443 173.7562 182.7711 170.1502 179.1651 170.1502 170.1502 173.7562 
##      921      922      923      924      925      926      927      928 
## 188.1800 170.1502 179.1651 189.9830 179.1651 198.9979 193.5889 193.5889 
##      929      930      931      932      933      934      935      936 
## 198.9979 206.2098 188.1800 193.5889 200.8008 179.1651 193.5889 193.5889 
##      937      938      939      940      941      942      943      944 
## 198.9979 177.3621 195.3919 179.1651 184.5740 200.8008 188.1800 200.8008 
##      945      946      947      948      949      950      951      952 
## 189.9830 188.1800 193.5889 193.5889 195.3919 195.3919 195.3919 182.7711 
##      953      954      955      956      957      958      959      960 
## 193.5889 200.8008 175.5592 177.3621 355.8567 413.5520 186.3770 283.7377 
##      961      962      963      964      965      966      967      968 
## 427.9758 211.6187 161.1354 161.1354 272.9199 245.8752 179.1651 415.3549 
##      969      970      971      972      973      974      975      976 
## 229.6484 229.6484 215.2246 215.2246 204.4068 202.6038 171.9532 198.9979 
##      977      978      979      980      981      982      983      984 
## 177.3621 229.6484 184.5740 155.7264 276.5258 175.5592 274.7228 218.8306 
##      985      986      987      988      989      990      991      992 
## 256.6931 175.5592 193.5889 227.8455 265.7079 226.0425 382.9014 235.0574 
##      993      994      995      996      997      998      999     1000 
## 247.6782 272.9199 272.9199 276.5258 325.2061 208.0127 146.7116 409.9460 
##     1001     1002     1003     1004     1005     1006     1007     1008 
## 337.8270 355.8567 354.0538 289.1466 283.7377 327.0091 289.1466 424.3698 
##     1009     1010     1011     1012     1013     1014     1015     1016 
## 240.4663 354.0538 188.1800 399.1281 238.6633 346.8419 427.9758 231.4514 
##     1017     1018     1019     1020     1021     1022     1023     1024 
## 283.7377 283.7377 361.2657 251.2841 254.8901 184.5740 298.1615 211.6187 
##     1025     1026     1027     1028     1029     1030     1031     1032 
## 229.6484 233.2544 283.7377 298.1615 229.6484 177.3621 177.3621 355.8567 
##     1033     1034     1035     1036     1037     1038     1039     1040 
## 189.9830 208.0127 208.0127 226.0425 298.1615 294.5556 222.4365 208.0127 
##     1041     1042     1043     1044     1045     1046     1047     1048 
## 227.8455 283.7377 294.5556 427.9758 272.9199 215.2246 215.2246 215.2246 
##     1049     1050     1051     1052     1053     1054     1055     1056 
## 258.4960 409.9460 226.0425 193.5889 280.1318 247.6782 272.9199 332.4180 
##     1057     1058     1059     1060     1061     1062     1063     1064 
## 213.4217 379.2954 175.5592 175.5592 164.7413 173.7562 153.9235 184.5740 
##     1065     1066     1067     1068     1069     1070     1071     1072 
## 197.1949 265.7079 202.6038 236.8603 337.8270 231.4514 247.6782 314.3883 
##     1073     1074     1075     1076     1077     1078     1079     1080 
## 345.0389 319.7972 177.3621 166.5443 171.9532 197.1949 197.1949 197.1949 
##     1081     1082     1083     1084     1085     1086     1087     1088 
## 213.4217 193.5889 247.6782 285.5407 319.7972 206.2098 206.2098 229.6484 
##     1089     1090     1091     1092     1093     1094     1095     1096 
## 256.6931 236.8603 182.7711 162.9383 175.5592 175.5592 175.5592 200.8008 
##     1097     1098     1099     1100     1101     1102     1103     1104 
## 197.1949 283.7377 244.0722 168.3473 175.5592 168.3473 175.5592 175.5592 
##     1105     1106     1107     1108     1109     1110     1111     1112 
## 211.6187 175.5592 274.7228 173.7562 211.6187 240.4663 211.6187 161.1354 
##     1113     1114     1115     1116     1117     1118     1119     1120 
## 175.5592 171.9532 217.0276 184.5740 157.5294 175.5592 157.5294 157.5294 
##     1121     1122     1123     1124     1125     1126     1127     1128 
## 175.5592 229.6484 175.5592 202.6038 269.3139 175.5592 222.4365 208.0127 
##     1129     1130     1131     1132     1133     1134     1135     1136 
## 229.6484 229.6484 229.6484 168.3473 175.5592 195.3919 198.9979 193.5889 
##     1137     1138     1139     1140     1141     1142     1143     1144 
## 175.5592 238.6633 175.5592 170.1502 144.9086 355.8567 202.6038 240.4663 
##     1145     1146     1147     1148     1149     1150     1151     1152 
## 177.3621 166.5443 170.1502 346.8419 247.6782 202.6038 274.7228 283.7377 
##     1153     1154     1155     1156     1157     1158     1159     1160 
## 179.1651 155.7264 200.8008 249.4812 166.5443 355.8567 157.5294 157.5294 
##     1161     1162     1163     1164     1165     1166     1167     1168 
## 189.9830 166.5443 164.7413 319.7972 197.1949 278.3288 189.9830 179.1651 
##     1169     1170     1171     1172     1173     1174     1175     1176 
## 202.6038 157.5294 175.5592 179.1651 173.7562 171.9532 240.4663 173.7562 
##     1177     1178     1179     1180     1181     1182     1183     1184 
## 175.5592 166.5443 193.5889 238.6633 175.5592 198.9979 164.7413 175.5592 
##     1185     1186     1187     1188     1189     1190     1191     1192 
## 175.5592 197.1949 198.9979 197.1949 204.4068 247.6782 209.8157 193.5889 
##     1193     1194     1195     1196     1197     1198     1199     1200 
## 204.4068 229.6484 265.7079 427.9758 274.7228 253.0871 355.8567 157.5294 
##     1201     1202     1203     1204     1205     1206     1207     1208 
## 182.7711 211.6187 175.5592 211.6187 177.3621 208.0127 175.5592 204.4068 
##     1209     1210     1211     1212     1213     1214     1215     1216 
## 175.5592 179.1651 179.1651 208.0127 208.0127 164.7413 175.5592 220.6336 
##     1217     1218     1219     1220     1221     1222     1223     1224 
## 211.6187 208.0127 175.5592 182.7711 175.5592 197.1949 191.7859 182.7711 
##     1225     1226     1227     1228     1229     1230     1231     1232 
## 171.9532 175.5592 171.9532 175.5592 182.7711 211.6187 289.1466 179.1651 
##     1233     1234     1235     1236     1237     1238     1239     1240 
## 175.5592 182.7711 173.7562 427.9758 171.9532 175.5592 171.9532 175.5592 
##     1241     1242     1243     1244     1245     1246     1247     1248 
## 171.9532 229.6484 198.9979 162.9383 184.5740 179.1651 175.5592 247.6782 
##     1249     1250     1251     1252     1253     1254     1255     1256 
## 193.5889 247.6782 391.9162 290.9496 184.5740 224.2395 244.0722 256.6931 
##     1257     1258     1259     1260     1261     1262     1263     1264 
## 197.1949 175.5592 289.1466 355.8567 175.5592 413.5520 180.9681 188.1800 
##     1265     1266     1267     1268     1269     1270     1271     1272 
## 294.5556 193.5889 177.3621 159.3324 175.5592 168.3473 173.7562 184.5740 
##     1273     1274     1275     1276     1277     1278     1279     1280 
## 211.6187 231.4514 153.9235 173.7562 224.2395 175.5592 211.6187 171.9532 
##     1281     1282     1283     1284     1285     1286     1287     1288 
## 152.1205 175.5592 229.6484 175.5592 157.5294 168.3473 166.5443 157.5294 
##     1289     1290     1291     1292     1293     1294     1295     1296 
## 166.5443 211.6187 198.9979 175.5592 166.5443 175.5592 202.6038 166.5443 
##     1297     1298     1299     1300     1301     1302     1303     1304 
## 177.3621 193.5889 211.6187 193.5889 215.2246 213.4217 213.4217 193.5889 
##     1305     1306     1307     1308     1309     1310     1311     1312 
## 213.4217 213.4217 233.2544 208.0127 175.5592 166.5443 179.1651 157.5294 
##     1313     1314     1315     1316     1317     1318     1319     1320 
## 184.5740 170.1502 175.5592 173.7562 175.5592 184.5740 229.6484 168.3473 
##     1321     1322     1323     1324     1325     1326     1327     1328 
## 229.6484 209.8157 231.4514 161.1354 179.1651 197.1949 265.7079 265.7079 
##     1329     1330     1331     1332     1333     1334     1335     1336 
## 159.3324 170.1502 200.8008 168.3473 173.7562 173.7562 170.1502 188.1800 
##     1337     1338     1339     1340     1341     1342     1343     1344 
## 175.5592 168.3473 175.5592 175.5592 175.5592 161.1354 202.6038 189.9830 
##     1345     1346     1347     1348     1349     1350     1351     1352 
## 166.5443 166.5443 175.5592 175.5592 166.5443 197.1949 166.5443 166.5443 
##     1353     1354     1355     1356     1357     1358     1359     1360 
## 188.1800 170.1502 168.3473 173.7562 193.5889 189.9830 224.2395 197.1949 
##     1361     1362     1363     1364     1365     1366     1367     1368 
## 217.0276 157.5294 218.8306 173.7562 164.7413 179.1651 175.5592 191.7859 
##     1369     1370     1371     1372     1373     1374     1375     1376 
## 175.5592 260.2990 218.8306 227.8455 208.0127 175.5592 148.5145 175.5592 
##     1377     1378     1379     1380     1381     1382     1383     1384 
## 244.0722 229.6484 166.5443 240.4663 179.1651 175.5592 231.4514 211.6187 
##     1385     1386     1387     1388     1389     1390     1391     1392 
## 175.5592 238.6633 211.6187 175.5592 173.7562 206.2098 175.5592 197.1949 
##     1393     1394     1395     1396     1397     1398     1399     1400 
## 204.4068 175.5592 193.5889 177.3621 189.9830 233.2544 166.5443 175.5592 
##     1401     1402     1403     1404     1405     1406     1407     1408 
## 175.5592 189.9830 217.0276 213.4217 166.5443 184.5740 193.5889 175.5592 
##     1409     1410     1411     1412     1413     1414     1415     1416 
## 175.5592 175.5592 175.5592 175.5592 193.5889 197.1949 206.2098 218.8306 
##     1417     1418     1419     1420     1421     1422     1423     1424 
## 175.5592 208.0127 229.6484 208.0127 202.6038 189.9830 209.8157 231.4514 
##     1425     1426     1427     1428     1429     1430     1431     1432 
## 175.5592 204.4068 189.9830 175.5592 193.5889 184.5740 202.6038 180.9681 
##     1433     1434     1435     1436     1437     1438     1439     1440 
## 171.9532 171.9532 208.0127 198.9979 200.8008 193.5889 184.5740 193.5889 
##     1441     1442     1443     1444     1445     1446     1447     1448 
## 175.5592 193.5889 197.1949 211.6187 202.6038 211.6187 215.2246 236.8603 
##     1449     1450     1451     1452     1453     1454     1455     1456 
## 202.6038 191.7859 195.3919 208.0127 229.6484 204.4068 227.8455 227.8455 
##     1457     1458     1459     1460     1461     1462     1463     1464 
## 193.5889 180.9681 193.5889 211.6187 222.4365 213.4217 244.0722 198.9979 
##     1465     1466     1467     1468     1469     1470     1471     1472 
## 222.4365 244.0722 198.9979 208.0127 211.6187 208.0127 198.9979 236.8603 
##     1473     1474     1475     1476     1477     1478     1479     1480 
## 208.0127 244.0722 208.0127 227.8455 208.0127 208.0127 208.0127 224.2395 
##     1481     1482     1483     1484     1485     1486     1487     1488 
## 224.2395 197.1949 197.1949 179.1651 247.6782 206.2098 175.5592 177.3621 
##     1489     1490     1491     1492     1493     1494     1495     1496 
## 173.7562 175.5592 208.0127 175.5592 233.2544 197.1949 179.1651 175.5592 
##     1497     1498     1499     1500     1501     1502     1503     1504 
## 175.5592 175.5592 175.5592 193.5889 191.7859 193.5889 206.2098 208.0127 
##     1505     1506     1507     1508     1509     1510     1511     1512 
## 191.7859 208.0127 229.6484 197.1949 208.0127 175.5592 189.9830 215.2246 
##     1513     1514     1515     1516     1517     1518     1519     1520 
## 215.2246 220.6336 260.2990 208.0127 193.5889 200.8008 211.6187 166.5443 
##     1521     1522     1523     1524     1525     1526     1527     1528 
## 166.5443 166.5443 164.7413 157.5294 166.5443 263.9050 202.6038 193.5889 
##     1529     1530     1531     1532     1533     1534     1535     1536 
## 184.5740 370.2805 247.6782 171.9532 161.1354 175.5592 175.5592 247.6782 
##     1537     1538     1539     1540     1541     1542     1543     1544 
## 189.9830 191.7859 200.8008 166.5443 193.5889 197.1949 162.9383 202.6038 
##     1545     1546     1547     1548     1549     1550     1551     1552 
## 202.6038 175.5592 175.5592 175.5592 180.9681 200.8008 184.5740 200.8008 
##     1553     1554     1555     1556     1557     1558     1559     1560 
## 157.5294 224.2395 193.5889 175.5592 161.1354 173.7562 175.5592 171.9532 
##     1561     1562     1563     1564     1565     1566     1567     1568 
## 175.5592 427.9758 168.3473 153.9235 179.1651 177.3621 287.3437 175.5592 
##     1569     1570     1571     1572     1573     1574     1575     1576 
## 157.5294 193.5889 202.6038 217.0276 197.1949 193.5889 211.6187 179.1651 
##     1577     1578     1579     1580     1581     1582     1583     1584 
## 197.1949 184.5740 193.5889 166.5443 337.8270 251.2841 171.9532 175.5592 
##     1585     1586     1587     1588     1589     1590     1591     1592 
## 251.2841 175.5592 184.5740 173.7562 179.1651 153.9235 236.8603 153.9235 
##     1593     1594     1595     1596     1597     1598     1599     1600 
## 211.6187 229.6484 198.9979 175.5592 175.5592 218.8306 265.7079 233.2544 
##     1601     1602     1603     1604     1605     1606     1607     1608 
## 208.0127 206.2098 213.4217 218.8306 265.7079 236.8603 179.1651 217.0276 
##     1609     1610     1611     1612     1613     1614     1615     1616 
## 175.5592 229.6484 224.2395 215.2246 211.6187 211.6187 283.7377 218.8306 
##     1617     1618     1619     1620     1621     1622     1623     1624 
## 224.2395 213.4217 177.3621 283.7377 197.1949 208.0127 168.3473 229.6484 
##     1625     1626     1627     1628     1629     1630     1631     1632 
## 197.1949 193.5889 213.4217 209.8157 211.6187 213.4217 222.4365 186.3770 
##     1633     1634     1635     1636     1637     1638     1639     1640 
## 202.6038 179.1651 180.9681 247.6782 283.7377 175.5592 391.9162 157.5294 
##     1641     1642     1643     1644     1645     1646     1647     1648 
## 179.1651 180.9681 189.9830 166.5443 139.4997 175.5592 359.4627 164.7413 
##     1649     1650     1651     1652     1653     1654     1655     1656 
## 218.8306 253.0871 220.6336 280.1318 341.4329 198.9979 258.4960 294.5556 
##     1657     1658     1659     1660     1661     1662     1663     1664 
## 253.0871 267.5109 247.6782 198.9979 208.0127 283.7377 283.7377 283.7377 
##     1665     1666     1667     1668     1669     1670     1671     1672 
## 283.7377 202.6038 198.9979 175.5592 206.2098 180.9681 215.2246 198.9979 
##     1673     1674     1675     1676     1677     1678     1679     1680 
## 274.7228 222.4365 375.6895 413.5520 247.6782 352.2508 359.4627 220.6336 
##     1681     1682     1683     1684     1685     1686     1687     1688 
## 164.7413 283.7377 202.6038 247.6782 197.1949 200.8008 238.6633 283.7377 
##     1689     1690     1691     1692     1693     1694     1695     1696 
## 188.1800 157.5294 359.4627 218.8306 229.6484 283.7377 272.9199 301.7675 
##     1697     1698     1699     1700     1701     1702     1703     1704 
## 427.9758 427.9758 296.3585 390.1133 164.7413 182.7711 189.9830 152.1205 
##     1705     1706 
## 175.5592 231.4514
\end{verbatim}

\end{document}
